// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeQ8KQdo-MoV4yKOyykDS8IpQiz-u8YQ8',
    appId: '1:435950511307:web:bffb3134ff4ee8ba93e74e',
    messagingSenderId: '435950511307',
    projectId: 'simple-chat-app20220510',
    authDomain: 'simple-chat-app20220510.firebaseapp.com',
    storageBucket: 'simple-chat-app20220510.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNLUu2upfqrAnff46kChGqYr8FnwM00kc',
    appId: '1:435950511307:android:21e9a5b9a33eb7e293e74e',
    messagingSenderId: '435950511307',
    projectId: 'simple-chat-app20220510',
    storageBucket: 'simple-chat-app20220510.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA91TCawPx_6JoLpPWldldFoAt4MU0hTmQ',
    appId: '1:435950511307:ios:709bc1faaa468e0493e74e',
    messagingSenderId: '435950511307',
    projectId: 'simple-chat-app20220510',
    storageBucket: 'simple-chat-app20220510.appspot.com',
    iosClientId: '435950511307-6apfhjo7f8s8uos3u1masdlfhdbrk5um.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
