// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoknoakaJrVmYkj6nC_ref2t1KKecSLdc',
    appId: '1:393806456610:web:76fb4858fe2cc88b1f277b',
    messagingSenderId: '393806456610',
    projectId: 'simple-chat-app-b25a4',
    authDomain: 'simple-chat-app-b25a4.firebaseapp.com',
    storageBucket: 'simple-chat-app-b25a4.appspot.com',
    measurementId: 'G-XD6BBK0Y30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJnLr5Sv-pS3btRawV4SCM4FvBj9Utas0',
    appId: '1:393806456610:android:5d4f62545df1501e1f277b',
    messagingSenderId: '393806456610',
    projectId: 'simple-chat-app-b25a4',
    storageBucket: 'simple-chat-app-b25a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoEM2wRetTHXTbSEWv_-DXqdEZtNv0qYc',
    appId: '1:393806456610:ios:7f65122fe81c78741f277b',
    messagingSenderId: '393806456610',
    projectId: 'simple-chat-app-b25a4',
    storageBucket: 'simple-chat-app-b25a4.appspot.com',
    iosClientId: '393806456610-ue6fc1pu1i0n340vnl1q2fid3aqs9e9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoEM2wRetTHXTbSEWv_-DXqdEZtNv0qYc',
    appId: '1:393806456610:ios:7f65122fe81c78741f277b',
    messagingSenderId: '393806456610',
    projectId: 'simple-chat-app-b25a4',
    storageBucket: 'simple-chat-app-b25a4.appspot.com',
    iosClientId: '393806456610-ue6fc1pu1i0n340vnl1q2fid3aqs9e9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
